<a href="https://colab.research.google.com/github/PrantoMondol11/Machine-learning-/blob/main/dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
X,y=make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
X=torch.from_numpy(X)

In [ ]:
X.type()

'torch.DoubleTensor'

In [ ]:
type(X)

torch.Tensor

In [ ]:
y=torch.from_numpy(y)

In [ ]:
from torch.utils.data import Dataset,DataLoader

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)

In [25]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels, transform=None):
        self.features = features
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.features)

    def __getitem__(self, index):
        x = self.features[index]
        y = self.labels[index]

        if self.transform is not None:
            x = self.transform(x)

        return x, y




In [ ]:
dataset=CustomDatasets(X,y)

In [ ]:
dataset.__getitem__(2)

(tensor([-2.8954,  1.9769], dtype=torch.float64), tensor(0))

In [ ]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [ ]:
for data in dataloader:
  print("-",data)



- [tensor([[-2.8954,  1.9769],
        [ 1.7273, -1.1858]], dtype=torch.float64), tensor([0, 1])]
- [tensor([[-0.7206, -0.9606],
        [-1.9629, -0.9923]], dtype=torch.float64), tensor([0, 0])]
- [tensor([[-0.5872, -1.9717],
        [ 1.7774,  1.5116]], dtype=torch.float64), tensor([0, 1])]
- [tensor([[ 1.8997,  0.8344],
        [-0.9382, -0.5430]], dtype=torch.float64), tensor([1, 1])]
- [tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]], dtype=torch.float64), tensor([1, 0])]


In [1]:
import numpy as np

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn


In [5]:
from torch.utils.data import DataLoader,Dataset

In [6]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [11]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [12]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],random_state=42,test_size=0.2)

In [13]:
X_train.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
68,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.04375,0.2111,0.08046,0.3274,1.1940,1.885,17.67,0.009549,0.08606,0.303800,0.033220,0.04197,0.009559,10.31,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
181,21.090,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,0.07398,0.6298,0.7629,4.414,81.46,0.004253,0.04759,0.038720,0.015670,0.01798,0.005295,26.68,33.48,176.50,2089.0,0.14910,0.75840,0.67800,0.29030,0.4098,0.12840
63,9.173,13.86,59.20,260.9,0.07721,0.08751,0.05988,0.02180,0.2341,0.06963,0.4098,2.2650,2.608,23.52,0.008738,0.03938,0.043120,0.015600,0.04192,0.005822,10.01,19.23,65.59,310.1,0.09836,0.16780,0.13970,0.05087,0.3282,0.08490
248,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.01615,0.1897,0.06329,0.2497,1.4930,1.497,16.64,0.007189,0.01035,0.010810,0.006245,0.02158,0.002619,12.25,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147
60,10.170,14.88,64.55,311.9,0.11340,0.08061,0.01084,0.01290,0.2743,0.06960,0.5158,1.4410,3.312,34.62,0.007514,0.01099,0.007665,0.008193,0.04183,0.005953,11.02,17.45,69.86,368.6,0.12750,0.09866,0.02168,0.02579,0.3557,0.08020


In [14]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [15]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [29]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels, transform=None):
        self.features = features
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.features)

    def __getitem__(self, index):
        x = self.features[index]
        y = self.labels[index]

        if self.transform is not None:
            x = self.transform(x)

        return x, y

In [37]:
dataset=CustomDataset(X_train,y_train)

In [38]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [39]:
import torch
import torch.nn as nn

In [48]:
model = nn.Sequential(
    nn.Linear(input_size, hidden_size),
    nn.Sigmoid(),
    nn.Linear(hidden_size, 2)
)


In [49]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [50]:
import torch

def train(model, train_loader, criterion, optimizer, epochs, device):
    model.to(device)

    for epoch in range(epochs):
        model.train()

        running_loss = 0.0
        correct = 0
        total = 0

        for X_batch, y_batch in train_loader:
            X_batch = X_batch.float().to(device)
            y_batch = y_batch.long().to(device)

            # Forward pass
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # Statistics
            running_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            total += y_batch.size(0)
            correct += (predicted == y_batch).sum().item()

        epoch_loss = running_loss / len(train_loader)
        epoch_acc = 100 * correct / total

        print(
            f"Epoch [{epoch+1}/{epochs}] "
            f"Loss: {epoch_loss:.4f} "
            f"Accuracy: {epoch_acc:.2f}%"
        )

In [51]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train(
    model=model,
    train_loader=dataloader,
    criterion=criterion,
    optimizer=optimizer,
    epochs=10,
    device=device
)

Epoch [1/10] Loss: 0.4953 Accuracy: 84.18%
Epoch [2/10] Loss: 0.2643 Accuracy: 94.73%
Epoch [3/10] Loss: 0.1691 Accuracy: 97.14%
Epoch [4/10] Loss: 0.1257 Accuracy: 97.36%
Epoch [5/10] Loss: 0.1038 Accuracy: 98.02%
Epoch [6/10] Loss: 0.0908 Accuracy: 98.24%
Epoch [7/10] Loss: 0.0824 Accuracy: 98.24%
Epoch [8/10] Loss: 0.0766 Accuracy: 98.02%
Epoch [9/10] Loss: 0.0724 Accuracy: 98.24%
Epoch [10/10] Loss: 0.0720 Accuracy: 98.24%
