<a href="https://colab.research.google.com/github/PrantoMondol11/Machine-learning-/blob/main/tarining_pipeline_custom_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN


In [6]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0])

In [8]:
from pandas.core.tools.datetimes import Scalar
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
X_train

array([[-0.53927354, -1.05730409, -0.59660446, ..., -1.07233201,
        -1.01387603, -1.3499445 ],
       [ 0.59658837,  0.27735848,  0.60584094, ...,  0.64346305,
         0.31069198, -0.13617177],
       [-0.55950518, -0.36911871, -0.59156099, ..., -0.33561435,
         0.88988197, -0.84720486],
       ...,
       [-0.41499349,  2.29788931, -0.46799618, ..., -0.80727533,
        -0.83452459, -1.07185641],
       [ 0.10813885, -1.3562129 ,  0.07585714, ..., -0.38940298,
        -0.47417627, -0.7643237 ],
       [ 2.00991274,  0.81724802,  1.87931509, ...,  1.3057161 ,
        -0.15167275, -0.50368427]])

In [10]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [11]:
y_test

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [21]:
X_train_tensor=torch.from_numpy(X_train)
y_train_tensor=torch.from_numpy(y_train)
X_test_tensor=torch.from_numpy(X_test)
y_test_tensor=torch.from_numpy(y_test)


In [42]:
class mynn():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    return torch.sigmoid(z)

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss


In [43]:
learning_rate=0.1
epochs=25

In [44]:
model=mynn(X_train_tensor)

for epoch in range(epochs):
    y_pred=model.forward(X_tain_tensor)
    loss= model.loss_function(y_pred,y_tain_tensor)
    print(f"Epoch:{epoch+1}, Loss:{loss.item()}")
    loss.backward()

    with torch.no_grad():
      model.weights-=learning_rate*model.weights.grad
      model.bias-=learning_rate*model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

Epoch:1, Loss:3.6726227226980295
Epoch:2, Loss:3.5481485167418376
Epoch:3, Loss:3.4197197232342527
Epoch:4, Loss:3.2828818290650594
Epoch:5, Loss:3.1413170180306382
Epoch:6, Loss:2.9986376627722118
Epoch:7, Loss:2.8462376799141924
Epoch:8, Loss:2.6861171574363243
Epoch:9, Loss:2.521343336196066
Epoch:10, Loss:2.356877401933833
Epoch:11, Loss:2.1885273379827046
Epoch:12, Loss:2.0239815126661327
Epoch:13, Loss:1.8656428008812218
Epoch:14, Loss:1.7134542801016772
Epoch:15, Loss:1.5715826564685935
Epoch:16, Loss:1.441653961774274
Epoch:17, Loss:1.3247470950690758
Epoch:18, Loss:1.2168660023937372
Epoch:19, Loss:1.1220684193416326
Epoch:20, Loss:1.0437611743916917
Epoch:21, Loss:0.9811376968766341
Epoch:22, Loss:0.9325737325122647
Epoch:23, Loss:0.8957959668509796
Epoch:24, Loss:0.8682249332764514
Epoch:25, Loss:0.8473983336267923


In [45]:
model.weights

tensor([[-0.3885],
        [ 0.3383],
        [ 0.0039],
        [ 0.1108],
        [-0.2833],
        [ 0.0358],
        [-0.4644],
        [ 0.2333],
        [-0.1105],
        [-0.1967],
        [ 0.0387],
        [-0.0859],
        [ 0.3546],
        [ 0.2848],
        [ 0.7036],
        [-0.0155],
        [ 0.0650],
        [-0.2513],
        [ 0.7234],
        [ 0.0011],
        [-0.3553],
        [-0.1320],
        [-0.0600],
        [ 0.2628],
        [ 0.0747],
        [ 0.4622],
        [ 0.2997],
        [ 0.1951],
        [-0.1595],
        [-0.3355]], dtype=torch.float64, requires_grad=True)

In [46]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
print(y_pred)

tensor([[0.2738],
        [0.3378],
        [0.9357],
        [0.6742],
        [0.2257],
        [0.4127],
        [0.8449],
        [0.2524],
        [0.8887],
        [0.6642],
        [0.1863],
        [0.9411],
        [0.1650],
        [0.8193],
        [0.9336],
        [0.4283],
        [0.3331],
        [0.2006],
        [0.5226],
        [0.1934],
        [0.3468],
        [0.3935],
        [0.4969],
        [0.6846],
        [0.5804],
        [0.1736],
        [0.6339],
        [0.7361],
        [0.3106],
        [0.3881],
        [1.0000],
        [0.3370],
        [0.7356],
        [0.2665],
        [0.4758],
        [0.8675],
        [0.7318],
        [0.2604],
        [0.2082],
        [0.7699],
        [0.2659],
        [0.7742],
        [0.6769],
        [0.1600],
        [0.3497],
        [0.3986],
        [0.3564],
        [0.8428],
        [0.5219],
        [0.2292],
        [0.3863],
        [0.3056],
        [0.4027],
        [0.4103],
        [0.3822],
        [0